/* Generated by Yosys 0.41+111 (git sha1 4b67f3757, clang++ 10.0.0-4ubuntu1 -fPIC -Os) */

/* top =  1  */
/* src = "../../counter16_wrapper.v:8.1-73.10" */
module counter16_wrapper(\Din_emu[0] , \Din_emu[1] , \Din_emu[2] , \Din_emu[3] , \Din_emu[4] , \Din_emu[5] , \Din_emu[6] , \Din_emu[7] , \Dout_emu[0] , \Dout_emu[1] , \Dout_emu[2] , \Dout_emu[3] , \Dout_emu[4] , \Dout_emu[5] , \Dout_emu[6] , \Dout_emu[7] , \Addr_emu[0] , \Addr_emu[1] , \Addr_emu[2] , load_emu, get_emu
, clk_emu, clk_dut);
  /* src = "../../counter16_wrapper.v:12.21-12.29" */
  input \Addr_emu[0] ;
  wire \Addr_emu[0] ;
  wire \Addr_emu[0]_IBUF_I_O ;
  /* src = "../../counter16_wrapper.v:12.21-12.29" */
  input \Addr_emu[1] ;
  wire \Addr_emu[1] ;
  wire \Addr_emu[1]_IBUF_I_O ;
  /* src = "../../counter16_wrapper.v:12.21-12.29" */
  input \Addr_emu[2] ;
  wire \Addr_emu[2] ;
  /* unused_bits = "0" */
  wire \Addr_emu[2]_IBUF_I_O ;
  /* src = "../../counter16_wrapper.v:33.17-33.20" */
  wire \Din[0] ;
  wire \Din[0]_LUT3_I1_1_F ;
  wire \Din[0]_LUT3_I1_2_F ;
  wire \Din[0]_LUT3_I1_3_F ;
  wire \Din[0]_LUT3_I1_F ;
  /* src = "../../counter16_wrapper.v:33.17-33.20" */
  wire \Din[1] ;
  wire \Din[1]_LUT4_I0_1_F ;
  wire \Din[1]_LUT4_I0_1_F_DFFC_D_Q ;
  wire \Din[1]_LUT4_I0_2_F ;
  wire \Din[1]_LUT4_I0_3_F ;
  wire \Din[1]_LUT4_I0_F ;
  /* src = "../../counter16_wrapper.v:33.17-33.20" */
  wire \Din[2] ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" */
  wire \Din[2]_LUT3_I0_1_F ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" */
  wire \Din[2]_LUT3_I0_F ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" */
  wire \Din[2]_LUT4_I0_1_F ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" */
  wire \Din[2]_LUT4_I0_2_F ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" */
  wire \Din[2]_LUT4_I0_3_F ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" */
  wire \Din[2]_LUT4_I0_F ;
  /* src = "../../counter16_wrapper.v:33.17-33.20" */
  wire \Din[3] ;
  wire \Din[3]_LUT4_I0_F ;
  wire \Din[3]_LUT4_I0_I3 ;
  /* src = "../../counter16_wrapper.v:10.21-10.28" */
  input \Din_emu[0] ;
  wire \Din_emu[0] ;
  /* src = "../../counter16_wrapper.v:10.21-10.28" */
  input \Din_emu[1] ;
  wire \Din_emu[1] ;
  /* src = "../../counter16_wrapper.v:10.21-10.28" */
  input \Din_emu[2] ;
  wire \Din_emu[2] ;
  /* src = "../../counter16_wrapper.v:10.21-10.28" */
  input \Din_emu[3] ;
  wire \Din_emu[3] ;
  /* src = "../../counter16_wrapper.v:10.21-10.28" */
  input \Din_emu[4] ;
  wire \Din_emu[4] ;
  /* src = "../../counter16_wrapper.v:10.21-10.28" */
  input \Din_emu[5] ;
  wire \Din_emu[5] ;
  /* src = "../../counter16_wrapper.v:10.21-10.28" */
  input \Din_emu[6] ;
  wire \Din_emu[6] ;
  /* unused_bits = "0" */
  wire \Din_emu[6]_IBUF_I_O ;
  /* src = "../../counter16_wrapper.v:10.21-10.28" */
  input \Din_emu[7] ;
  wire \Din_emu[7] ;
  /* unused_bits = "0" */
  wire \Din_emu[7]_IBUF_I_O ;
  /* src = "../../counter16_wrapper.v:11.21-11.29" */
  output \Dout_emu[0] ;
  wire \Dout_emu[0] ;
  wire \Dout_emu[0]_OBUF_O_I ;
  /* src = "../../counter16_wrapper.v:11.21-11.29" */
  output \Dout_emu[1] ;
  wire \Dout_emu[1] ;
  wire \Dout_emu[1]_OBUF_O_I ;
  /* src = "../../counter16_wrapper.v:11.21-11.29" */
  output \Dout_emu[2] ;
  wire \Dout_emu[2] ;
  wire \Dout_emu[2]_OBUF_O_I ;
  /* src = "../../counter16_wrapper.v:11.21-11.29" */
  output \Dout_emu[3] ;
  wire \Dout_emu[3] ;
  wire \Dout_emu[3]_OBUF_O_I ;
  /* src = "../../counter16_wrapper.v:11.21-11.29" */
  output \Dout_emu[4] ;
  wire \Dout_emu[4] ;
  wire \Dout_emu[4]_OBUF_O_I ;
  /* src = "../../counter16_wrapper.v:11.21-11.29" */
  output \Dout_emu[5] ;
  wire \Dout_emu[5] ;
  wire \Dout_emu[5]_OBUF_O_I ;
  /* src = "../../counter16_wrapper.v:11.21-11.29" */
  output \Dout_emu[6] ;
  wire \Dout_emu[6] ;
  wire \Dout_emu[6]_OBUF_O_I ;
  /* src = "../../counter16_wrapper.v:11.21-11.29" */
  output \Dout_emu[7] ;
  wire \Dout_emu[7] ;
  wire \Dout_emu[7]_OBUF_O_I ;
  /* src = "../../counter16_wrapper.v:14.21-14.28" */
  input clk_dut;
  wire clk_dut;
  /* src = "../../counter16_wrapper.v:13.40-13.47" */
  input clk_emu;
  wire clk_emu;
  wire clk_emu_IBUF_I_O;
  /* src = "../../counter16_wrapper.v:13.31-13.38" */
  input get_emu;
  wire get_emu;
  wire get_emu_IBUF_I_O;
  wire get_emu_IBUF_I_O_LUT2_I1_1_F;
  wire get_emu_IBUF_I_O_LUT2_I1_F;
  /* src = "../../counter16_wrapper.v:13.21-13.29" */
  input load_emu;
  wire load_emu;
  wire load_emu_IBUF_I_O;
  /* src = "../../counter16_wrapper.v:32.17-32.21" */
  wire nCLR;
  wire nCLR_LUT1_I0_F;
  /* src = "../../counter16_wrapper.v:32.23-32.28" */
  wire nLOAD;
  wire \stimIn[0][0] ;
  wire \stimIn[0][0]_DFFE_Q_D ;
  wire \stimIn[0][1] ;
  wire \stimIn[0][1]_DFFE_Q_D ;
  wire \stimIn[0][2] ;
  wire \stimIn[0][2]_DFFE_Q_D ;
  wire \stimIn[0][3] ;
  wire \stimIn[0][3]_DFFE_Q_D ;
  wire \stimIn[0][4] ;
  wire \stimIn[0][4]_DFFE_Q_D ;
  wire \stimIn[0][5] ;
  wire \stimIn[0][5]_DFFE_Q_D ;
  wire \stimIn[0][6] ;
  wire \stimIn[0][7] ;
  /* hdlname = "u_counter16 CLK" */
  /* src = "../../../source/counter16.v:12.21-12.24" */
  wire \u_counter16.CLK ;
  /* hdlname = "u_counter16 Din" */
  /* src = "../../../source/counter16.v:14.21-14.24" */
  wire \u_counter16.Din[0] ;
  /* hdlname = "u_counter16 Din" */
  /* src = "../../../source/counter16.v:14.21-14.24" */
  wire \u_counter16.Din[1] ;
  /* hdlname = "u_counter16 Din" */
  /* src = "../../../source/counter16.v:14.21-14.24" */
  wire \u_counter16.Din[2] ;
  /* hdlname = "u_counter16 Din" */
  /* src = "../../../source/counter16.v:14.21-14.24" */
  wire \u_counter16.Din[3] ;
  /* hdlname = "u_counter16 nCLR" */
  /* src = "../../../source/counter16.v:13.21-13.25" */
  wire \u_counter16.nCLR ;
  /* hdlname = "u_counter16 nLOAD" */
  /* src = "../../../source/counter16.v:13.27-13.32" */
  wire \u_counter16.nLOAD ;
  /* hdlname = "u_counter16 u_LS163x0 CLK" */
  /* src = "../../../source/LS163.v:5.21-5.24" */
  wire \u_counter16.u_LS163x0.CLK ;
  /* hdlname = "u_counter16 u_LS163x0 Din" */
  /* src = "../../../source/LS163.v:7.21-7.24" */
  wire \u_counter16.u_LS163x0.Din[0] ;
  /* hdlname = "u_counter16 u_LS163x0 Din" */
  /* src = "../../../source/LS163.v:7.21-7.24" */
  wire \u_counter16.u_LS163x0.Din[1] ;
  /* hdlname = "u_counter16 u_LS163x0 Din" */
  /* src = "../../../source/LS163.v:7.21-7.24" */
  wire \u_counter16.u_LS163x0.Din[2] ;
  /* hdlname = "u_counter16 u_LS163x0 Din" */
  /* src = "../../../source/LS163.v:7.21-7.24" */
  wire \u_counter16.u_LS163x0.Din[3] ;
  /* hdlname = "u_counter16 u_LS163x0 nCLR" */
  /* src = "../../../source/LS163.v:5.26-5.30" */
  wire \u_counter16.u_LS163x0.nCLR ;
  /* hdlname = "u_counter16 u_LS163x0 nLOAD" */
  /* src = "../../../source/LS163.v:5.32-5.37" */
  wire \u_counter16.u_LS163x0.nLOAD ;
  /* hdlname = "u_counter16 u_LS163x1 CLK" */
  /* src = "../../../source/LS163.v:5.21-5.24" */
  wire \u_counter16.u_LS163x1.CLK ;
  /* hdlname = "u_counter16 u_LS163x1 Din" */
  /* src = "../../../source/LS163.v:7.21-7.24" */
  wire \u_counter16.u_LS163x1.Din[0] ;
  /* hdlname = "u_counter16 u_LS163x1 Din" */
  /* src = "../../../source/LS163.v:7.21-7.24" */
  wire \u_counter16.u_LS163x1.Din[1] ;
  /* hdlname = "u_counter16 u_LS163x1 Din" */
  /* src = "../../../source/LS163.v:7.21-7.24" */
  wire \u_counter16.u_LS163x1.Din[2] ;
  /* hdlname = "u_counter16 u_LS163x1 Din" */
  /* src = "../../../source/LS163.v:7.21-7.24" */
  wire \u_counter16.u_LS163x1.Din[3] ;
  /* hdlname = "u_counter16 u_LS163x1 nCLR" */
  /* src = "../../../source/LS163.v:5.26-5.30" */
  wire \u_counter16.u_LS163x1.nCLR ;
  /* hdlname = "u_counter16 u_LS163x1 nLOAD" */
  /* src = "../../../source/LS163.v:5.32-5.37" */
  wire \u_counter16.u_LS163x1.nLOAD ;
  /* hdlname = "u_counter16 u_LS163x2 CLK" */
  /* src = "../../../source/LS163.v:5.21-5.24" */
  wire \u_counter16.u_LS163x2.CLK ;
  /* hdlname = "u_counter16 u_LS163x2 Din" */
  /* src = "../../../source/LS163.v:7.21-7.24" */
  wire \u_counter16.u_LS163x2.Din[0] ;
  /* hdlname = "u_counter16 u_LS163x2 Din" */
  /* src = "../../../source/LS163.v:7.21-7.24" */
  wire \u_counter16.u_LS163x2.Din[1] ;
  /* hdlname = "u_counter16 u_LS163x2 Din" */
  /* src = "../../../source/LS163.v:7.21-7.24" */
  wire \u_counter16.u_LS163x2.Din[2] ;
  /* hdlname = "u_counter16 u_LS163x2 Din" */
  /* src = "../../../source/LS163.v:7.21-7.24" */
  wire \u_counter16.u_LS163x2.Din[3] ;
  /* hdlname = "u_counter16 u_LS163x2 nCLR" */
  /* src = "../../../source/LS163.v:5.26-5.30" */
  wire \u_counter16.u_LS163x2.nCLR ;
  /* hdlname = "u_counter16 u_LS163x2 nLOAD" */
  /* src = "../../../source/LS163.v:5.32-5.37" */
  wire \u_counter16.u_LS163x2.nLOAD ;
  /* hdlname = "u_counter16 u_LS163x3 CLK" */
  /* src = "../../../source/LS163.v:5.21-5.24" */
  wire \u_counter16.u_LS163x3.CLK ;
  /* hdlname = "u_counter16 u_LS163x3 Din" */
  /* src = "../../../source/LS163.v:7.21-7.24" */
  wire \u_counter16.u_LS163x3.Din[0] ;
  /* hdlname = "u_counter16 u_LS163x3 Din" */
  /* src = "../../../source/LS163.v:7.21-7.24" */
  wire \u_counter16.u_LS163x3.Din[1] ;
  /* hdlname = "u_counter16 u_LS163x3 Din" */
  /* src = "../../../source/LS163.v:7.21-7.24" */
  wire \u_counter16.u_LS163x3.Din[2] ;
  /* hdlname = "u_counter16 u_LS163x3 Din" */
  /* src = "../../../source/LS163.v:7.21-7.24" */
  wire \u_counter16.u_LS163x3.Din[3] ;
  /* hdlname = "u_counter16 u_LS163x3 nCLR" */
  /* src = "../../../source/LS163.v:5.26-5.30" */
  wire \u_counter16.u_LS163x3.nCLR ;
  /* hdlname = "u_counter16 u_LS163x3 nLOAD" */
  /* src = "../../../source/LS163.v:5.32-5.37" */
  wire \u_counter16.u_LS163x3.nLOAD ;
  /* src = "../../counter16_wrapper.v:29.17-29.24" */
  wire \vectOut[0][0] ;
  wire \vectOut[0][0]_DFFE_Q_D ;
  /* src = "../../counter16_wrapper.v:29.17-29.24" */
  wire \vectOut[0][1] ;
  /* src = "../../counter16_wrapper.v:29.17-29.24" */
  wire \vectOut[0][2] ;
  wire \vectOut[0][2]_DFFE_Q_D ;
  wire \vectOut[0][2]_DFFE_Q_D_DFFC_Q_D ;
  /* src = "../../counter16_wrapper.v:29.17-29.24" */
  wire \vectOut[0][3] ;
  wire \vectOut[0][3]_DFFE_Q_D ;
  /* src = "../../counter16_wrapper.v:29.17-29.24" */
  wire \vectOut[0][4] ;
  wire \vectOut[0][4]_DFFE_Q_D ;
  wire \vectOut[0][4]_LUT4_I2_F ;
  /* src = "../../counter16_wrapper.v:29.17-29.24" */
  wire \vectOut[0][5] ;
  wire \vectOut[0][5]_DFFE_Q_D ;
  wire \vectOut[0][5]_LUT4_I2_F ;
  /* src = "../../counter16_wrapper.v:29.17-29.24" */
  wire \vectOut[0][6] ;
  wire \vectOut[0][6]_DFFE_Q_D ;
  wire \vectOut[0][6]_DFFE_Q_D_DFFCE_Q_D ;
  wire \vectOut[0][6]_LUT4_I2_F ;
  /* src = "../../counter16_wrapper.v:29.17-29.24" */
  wire \vectOut[0][7] ;
  wire \vectOut[0][7]_DFFE_Q_D ;
  wire \vectOut[0][7]_DFFE_Q_D_DFFCE_Q_CE ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" */
  wire \vectOut[0][7]_DFFE_Q_D_DFFCE_Q_CE_MUX2_LUT5_O_I0 ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" */
  wire \vectOut[0][7]_DFFE_Q_D_DFFCE_Q_CE_MUX2_LUT5_O_I1 ;
  wire \vectOut[0][7]_DFFE_Q_D_DFFCE_Q_D ;
  wire \vectOut[0][7]_DFFE_Q_D_LUT4_I2_I3 ;
  /* src = "../../counter16_wrapper.v:29.17-29.24" */
  wire \vectOut[1][0] ;
  wire \vectOut[1][0]_DFFE_Q_D ;
  /* src = "../../counter16_wrapper.v:29.17-29.24" */
  wire \vectOut[1][1] ;
  wire \vectOut[1][1]_DFFE_Q_D ;
  wire \vectOut[1][1]_LUT4_I2_F ;
  /* src = "../../counter16_wrapper.v:29.17-29.24" */
  wire \vectOut[1][2] ;
  wire \vectOut[1][2]_DFFE_Q_D ;
  wire \vectOut[1][2]_LUT4_I2_F ;
  /* src = "../../counter16_wrapper.v:29.17-29.24" */
  wire \vectOut[1][3] ;
  wire \vectOut[1][3]_LUT4_I2_F ;
  /* src = "../../counter16_wrapper.v:29.17-29.24" */
  wire \vectOut[1][4] ;
  wire \vectOut[1][4]_DFFE_Q_D ;
  /* src = "../../counter16_wrapper.v:29.17-29.24" */
  wire \vectOut[1][5] ;
  wire \vectOut[1][5]_DFFE_Q_D ;
  /* src = "../../counter16_wrapper.v:29.17-29.24" */
  wire \vectOut[1][6] ;
  wire \vectOut[1][6]_DFFE_Q_D ;
  wire \vectOut[1][6]_DFFE_Q_D_DFFCE_Q_D ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" */
  wire \vectOut[1][6]_DFFE_Q_D_MUX2_LUT5_S0_I0 ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" */
  wire \vectOut[1][6]_DFFE_Q_D_MUX2_LUT5_S0_I1 ;
  /* src = "../../counter16_wrapper.v:29.17-29.24" */
  wire \vectOut[1][7] ;
  wire \vectOut[1][7]_DFFE_Q_D ;
  wire \vectOut[1][7]_DFFE_Q_D_DFFCE_Q_D ;
  wire \vectOut[1][7]_LUT4_I2_F ;
  wire \vectOut[2] ;
  wire \vectOut[2]_DFFE_Q_D ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" */
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_I0 ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" */
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_I1 ;
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_I1_LUT4_F_I2 ;
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_I1_LUT4_F_I2_LUT4_I3_F ;
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_I1_LUT4_F_I2_LUT4_I3_F_DFFCE_D_Q ;
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_I1_LUT4_F_I3 ;
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0 ;
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_LUT2_I1_F ;
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_LUT2_I1_F_DFFCE_CE_D ;
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_LUT3_I2_F ;
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_LUT3_I2_I1 ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:169.9-169.11" */
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0 ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:163.9-163.11" */
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0 ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:157.9-157.11" */
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0 ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" */
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" */
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:157.13-157.15" */
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1 ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" */
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" */
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:163.13-163.15" */
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1 ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:157.9-157.11" */
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0 ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" */
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" */
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:157.13-157.15" */
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1 ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" */
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" */
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:169.13-169.15" */
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1 ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/local/bin/../share/yosys/gowin/cells_map.v:163.9-163.11" */
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0 ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/local/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:157.9-157.11" */
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0 ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/local/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" */
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/local/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" */
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/local/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:157.13-157.15" */
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1 ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/local/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" */
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/local/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" */
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/local/bin/../share/yosys/gowin/cells_map.v:163.13-163.15" */
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1 ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/local/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:157.9-157.11" */
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0 ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/local/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" */
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/local/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" */
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/local/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:157.13-157.15" */
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1 ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/local/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" */
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/local/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" */
  wire \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:151.9-151.11" */
  wire \vectOut[2]_MUX2_LUT5_S0_I0 ;
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:151.13-151.15" */
  wire \vectOut[2]_MUX2_LUT5_S0_I1 ;
  wire \vectOut[2]_MUX2_LUT5_S0_O ;
  /* keep = 1 */
  IBUF \Addr_emu[0]_IBUF_I  (
    .I(\Addr_emu[0] ),
    .O(\Addr_emu[0]_IBUF_I_O )
  );
  /* keep = 1 */
  IBUF \Addr_emu[1]_IBUF_I  (
    .I(\Addr_emu[1] ),
    .O(\Addr_emu[1]_IBUF_I_O )
  );
  /* keep = 1 */
  IBUF \Addr_emu[2]_IBUF_I  (
    .I(\Addr_emu[2] ),
    .O(\Addr_emu[2]_IBUF_I_O )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE \Din[0]_DFFE_Q  (
    .CE(load_emu_IBUF_I_O),
    .CLK(clk_emu_IBUF_I_O),
    .D(\stimIn[0][0] ),
    .Q(\Din[0] )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:143.23-144.37" */
  LUT3 \Din[0]_LUT3_I1  (
    .F(\Din[0]_LUT3_I1_F ),
    .I0(nLOAD),
    .I1(\Din[0] ),
    .I2(\vectOut[0][4]_DFFE_Q_D )
  );
  defparam \Din[0]_LUT3_I1 .INIT = 8'h4e;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:143.23-144.37" */
  LUT3 \Din[0]_LUT3_I1_1  (
    .F(\Din[0]_LUT3_I1_1_F ),
    .I0(nLOAD),
    .I1(\Din[0] ),
    .I2(\vectOut[0][0]_DFFE_Q_D )
  );
  defparam \Din[0]_LUT3_I1_1 .INIT = 8'h4e;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:143.23-144.37" */
  LUT3 \Din[0]_LUT3_I1_2  (
    .F(\Din[0]_LUT3_I1_2_F ),
    .I0(nLOAD),
    .I1(\Din[0] ),
    .I2(\vectOut[1][0]_DFFE_Q_D )
  );
  defparam \Din[0]_LUT3_I1_2 .INIT = 8'h4e;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:143.23-144.37" */
  LUT3 \Din[0]_LUT3_I1_3  (
    .F(\Din[0]_LUT3_I1_3_F ),
    .I0(nLOAD),
    .I1(\Din[0] ),
    .I2(\vectOut[1][4]_DFFE_Q_D )
  );
  defparam \Din[0]_LUT3_I1_3 .INIT = 8'h4e;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE \Din[1]_DFFE_Q  (
    .CE(load_emu_IBUF_I_O),
    .CLK(clk_emu_IBUF_I_O),
    .D(\stimIn[0][1] ),
    .Q(\Din[1] )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT4 \Din[1]_LUT4_I0  (
    .F(\Din[1]_LUT4_I0_F ),
    .I0(\Din[1] ),
    .I1(nLOAD),
    .I2(\vectOut[0][5]_DFFE_Q_D ),
    .I3(\vectOut[0][4]_DFFE_Q_D )
  );
  defparam \Din[1]_LUT4_I0 .INIT = 16'h2ee2;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT4 \Din[1]_LUT4_I0_1  (
    .F(\Din[1]_LUT4_I0_1_F ),
    .I0(\Din[1] ),
    .I1(nLOAD),
    .I2(\Din[1]_LUT4_I0_1_F_DFFC_D_Q ),
    .I3(\vectOut[0][0]_DFFE_Q_D )
  );
  defparam \Din[1]_LUT4_I0_1 .INIT = 16'h2ee2;
  /* module_not_derived = 1 */
  /* src = "../../../source/LS163.v:12.5-23.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:91.7-91.59" */
  DFFC \Din[1]_LUT4_I0_1_F_DFFC_D  (
    .CLEAR(nCLR_LUT1_I0_F),
    .CLK(\u_counter16.CLK ),
    .D(\Din[1]_LUT4_I0_1_F ),
    .Q(\Din[1]_LUT4_I0_1_F_DFFC_D_Q )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT4 \Din[1]_LUT4_I0_2  (
    .F(\Din[1]_LUT4_I0_2_F ),
    .I0(\Din[1] ),
    .I1(nLOAD),
    .I2(\vectOut[1][0]_DFFE_Q_D ),
    .I3(\vectOut[1][1]_DFFE_Q_D )
  );
  defparam \Din[1]_LUT4_I0_2 .INIT = 16'h2ee2;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT4 \Din[1]_LUT4_I0_3  (
    .F(\Din[1]_LUT4_I0_3_F ),
    .I0(\Din[1] ),
    .I1(nLOAD),
    .I2(\vectOut[1][4]_DFFE_Q_D ),
    .I3(\vectOut[1][5]_DFFE_Q_D )
  );
  defparam \Din[1]_LUT4_I0_3 .INIT = 16'h2ee2;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE \Din[2]_DFFE_Q  (
    .CE(load_emu_IBUF_I_O),
    .CLK(clk_emu_IBUF_I_O),
    .D(\stimIn[0][2] ),
    .Q(\Din[2] )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT3 \Din[2]_LUT3_I0  (
    .F(\Din[2]_LUT3_I0_F ),
    .I0(\Din[2] ),
    .I1(nLOAD),
    .I2(\vectOut[0][6]_DFFE_Q_D )
  );
  defparam \Din[2]_LUT3_I0 .INIT = 8'he2;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT3 \Din[2]_LUT3_I0_1  (
    .F(\Din[2]_LUT3_I0_1_F ),
    .I0(\Din[2] ),
    .I1(nLOAD),
    .I2(\vectOut[0][2]_DFFE_Q_D )
  );
  defparam \Din[2]_LUT3_I0_1 .INIT = 8'he2;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" */
  MUX2_LUT5 \Din[2]_LUT3_I0_1_F_MUX2_LUT5_I0  (
    .I0(\Din[2]_LUT3_I0_1_F ),
    .I1(\Din[2]_LUT4_I0_1_F ),
    .O(\vectOut[0][2]_DFFE_Q_D_DFFC_Q_D ),
    .S0(\vectOut[0][0]_DFFE_Q_D )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" */
  MUX2_LUT5 \Din[2]_LUT3_I0_F_MUX2_LUT5_I0  (
    .I0(\Din[2]_LUT3_I0_F ),
    .I1(\Din[2]_LUT4_I0_F ),
    .O(\vectOut[0][6]_DFFE_Q_D_DFFCE_Q_D ),
    .S0(\vectOut[0][4]_DFFE_Q_D )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT4 \Din[2]_LUT4_I0  (
    .F(\Din[2]_LUT4_I0_F ),
    .I0(\Din[2] ),
    .I1(nLOAD),
    .I2(\vectOut[0][5]_DFFE_Q_D ),
    .I3(\vectOut[0][6]_DFFE_Q_D )
  );
  defparam \Din[2]_LUT4_I0 .INIT = 16'h2ee2;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT4 \Din[2]_LUT4_I0_1  (
    .F(\Din[2]_LUT4_I0_1_F ),
    .I0(\Din[2] ),
    .I1(nLOAD),
    .I2(\vectOut[0][2]_DFFE_Q_D ),
    .I3(\Din[1]_LUT4_I0_1_F_DFFC_D_Q )
  );
  defparam \Din[2]_LUT4_I0_1 .INIT = 16'h2ee2;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT4 \Din[2]_LUT4_I0_2  (
    .F(\Din[2]_LUT4_I0_2_F ),
    .I0(\Din[2] ),
    .I1(nLOAD),
    .I2(\vectOut[1][0]_DFFE_Q_D ),
    .I3(\vectOut[1][1]_DFFE_Q_D )
  );
  defparam \Din[2]_LUT4_I0_2 .INIT = 16'h2eee;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT4 \Din[2]_LUT4_I0_3  (
    .F(\Din[2]_LUT4_I0_3_F ),
    .I0(\Din[2] ),
    .I1(nLOAD),
    .I2(\vectOut[1][0]_DFFE_Q_D ),
    .I3(\vectOut[1][1]_DFFE_Q_D )
  );
  defparam \Din[2]_LUT4_I0_3 .INIT = 16'he222;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" */
  MUX2_LUT5 \Din[2]_LUT4_I0_3_F_MUX2_LUT5_I0  (
    .I0(\Din[2]_LUT4_I0_3_F ),
    .I1(\Din[2]_LUT4_I0_2_F ),
    .O(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_LUT2_I1_F_DFFCE_CE_D ),
    .S0(\vectOut[1][2]_DFFE_Q_D )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE \Din[3]_DFFE_Q  (
    .CE(load_emu_IBUF_I_O),
    .CLK(clk_emu_IBUF_I_O),
    .D(\stimIn[0][3] ),
    .Q(\Din[3] )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT4 \Din[3]_LUT4_I0  (
    .F(\Din[3]_LUT4_I0_F ),
    .I0(\Din[3] ),
    .I1(nLOAD),
    .I2(\vectOut[0][3]_DFFE_Q_D ),
    .I3(\Din[3]_LUT4_I0_I3 )
  );
  defparam \Din[3]_LUT4_I0 .INIT = 16'h2ee2;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:143.23-144.37" */
  LUT3 \Din[3]_LUT4_I0_I3_LUT3_F  (
    .F(\Din[3]_LUT4_I0_I3 ),
    .I0(\vectOut[0][2]_DFFE_Q_D ),
    .I1(\Din[1]_LUT4_I0_1_F_DFFC_D_Q ),
    .I2(\vectOut[0][0]_DFFE_Q_D )
  );
  defparam \Din[3]_LUT4_I0_I3_LUT3_F .INIT = 8'h80;
  /* keep = 1 */
  IBUF \Din_emu[0]_IBUF_I  (
    .I(\Din_emu[0] ),
    .O(\stimIn[0][0]_DFFE_Q_D )
  );
  /* keep = 1 */
  IBUF \Din_emu[1]_IBUF_I  (
    .I(\Din_emu[1] ),
    .O(\stimIn[0][1]_DFFE_Q_D )
  );
  /* keep = 1 */
  IBUF \Din_emu[2]_IBUF_I  (
    .I(\Din_emu[2] ),
    .O(\stimIn[0][2]_DFFE_Q_D )
  );
  /* keep = 1 */
  IBUF \Din_emu[3]_IBUF_I  (
    .I(\Din_emu[3] ),
    .O(\stimIn[0][3]_DFFE_Q_D )
  );
  /* keep = 1 */
  IBUF \Din_emu[4]_IBUF_I  (
    .I(\Din_emu[4] ),
    .O(\stimIn[0][4]_DFFE_Q_D )
  );
  /* keep = 1 */
  IBUF \Din_emu[5]_IBUF_I  (
    .I(\Din_emu[5] ),
    .O(\stimIn[0][5]_DFFE_Q_D )
  );
  /* keep = 1 */
  IBUF \Din_emu[6]_IBUF_I  (
    .I(\Din_emu[6] ),
    .O(\Din_emu[6]_IBUF_I_O )
  );
  /* keep = 1 */
  IBUF \Din_emu[7]_IBUF_I  (
    .I(\Din_emu[7] ),
    .O(\Din_emu[7]_IBUF_I_O )
  );
  /* keep = 1 */
  OBUF \Dout_emu[0]_OBUF_O  (
    .I(\Dout_emu[0]_OBUF_O_I ),
    .O(\Dout_emu[0] )
  );
  /* module_not_derived = 1 */
  /* src = "../../counter16_wrapper.v:43.5-63.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE \Dout_emu[0]_OBUF_O_I_DFFE_Q  (
    .CE(get_emu_IBUF_I_O_LUT2_I1_F),
    .CLK(clk_emu_IBUF_I_O),
    .D(\vectOut[2]_MUX2_LUT5_S0_O ),
    .Q(\Dout_emu[0]_OBUF_O_I )
  );
  /* keep = 1 */
  OBUF \Dout_emu[1]_OBUF_O  (
    .I(\Dout_emu[1]_OBUF_O_I ),
    .O(\Dout_emu[1] )
  );
  /* module_not_derived = 1 */
  /* src = "../../counter16_wrapper.v:43.5-63.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE \Dout_emu[1]_OBUF_O_I_DFFE_Q  (
    .CE(get_emu_IBUF_I_O_LUT2_I1_F),
    .CLK(clk_emu_IBUF_I_O),
    .D(\vectOut[1][1]_LUT4_I2_F ),
    .Q(\Dout_emu[1]_OBUF_O_I )
  );
  /* keep = 1 */
  OBUF \Dout_emu[2]_OBUF_O  (
    .I(\Dout_emu[2]_OBUF_O_I ),
    .O(\Dout_emu[2] )
  );
  /* module_not_derived = 1 */
  /* src = "../../counter16_wrapper.v:43.5-63.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE \Dout_emu[2]_OBUF_O_I_DFFE_Q  (
    .CE(get_emu_IBUF_I_O_LUT2_I1_F),
    .CLK(clk_emu_IBUF_I_O),
    .D(\vectOut[1][2]_LUT4_I2_F ),
    .Q(\Dout_emu[2]_OBUF_O_I )
  );
  /* keep = 1 */
  OBUF \Dout_emu[3]_OBUF_O  (
    .I(\Dout_emu[3]_OBUF_O_I ),
    .O(\Dout_emu[3] )
  );
  /* module_not_derived = 1 */
  /* src = "../../counter16_wrapper.v:43.5-63.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE \Dout_emu[3]_OBUF_O_I_DFFE_Q  (
    .CE(get_emu_IBUF_I_O_LUT2_I1_F),
    .CLK(clk_emu_IBUF_I_O),
    .D(\vectOut[1][3]_LUT4_I2_F ),
    .Q(\Dout_emu[3]_OBUF_O_I )
  );
  /* keep = 1 */
  OBUF \Dout_emu[4]_OBUF_O  (
    .I(\Dout_emu[4]_OBUF_O_I ),
    .O(\Dout_emu[4] )
  );
  /* module_not_derived = 1 */
  /* src = "../../counter16_wrapper.v:43.5-63.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE \Dout_emu[4]_OBUF_O_I_DFFE_Q  (
    .CE(get_emu_IBUF_I_O_LUT2_I1_F),
    .CLK(clk_emu_IBUF_I_O),
    .D(\vectOut[0][4]_LUT4_I2_F ),
    .Q(\Dout_emu[4]_OBUF_O_I )
  );
  /* keep = 1 */
  OBUF \Dout_emu[5]_OBUF_O  (
    .I(\Dout_emu[5]_OBUF_O_I ),
    .O(\Dout_emu[5] )
  );
  /* module_not_derived = 1 */
  /* src = "../../counter16_wrapper.v:43.5-63.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE \Dout_emu[5]_OBUF_O_I_DFFE_Q  (
    .CE(get_emu_IBUF_I_O_LUT2_I1_F),
    .CLK(clk_emu_IBUF_I_O),
    .D(\vectOut[0][5]_LUT4_I2_F ),
    .Q(\Dout_emu[5]_OBUF_O_I )
  );
  /* keep = 1 */
  OBUF \Dout_emu[6]_OBUF_O  (
    .I(\Dout_emu[6]_OBUF_O_I ),
    .O(\Dout_emu[6] )
  );
  /* module_not_derived = 1 */
  /* src = "../../counter16_wrapper.v:43.5-63.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE \Dout_emu[6]_OBUF_O_I_DFFE_Q  (
    .CE(get_emu_IBUF_I_O_LUT2_I1_F),
    .CLK(clk_emu_IBUF_I_O),
    .D(\vectOut[0][6]_LUT4_I2_F ),
    .Q(\Dout_emu[6]_OBUF_O_I )
  );
  /* keep = 1 */
  OBUF \Dout_emu[7]_OBUF_O  (
    .I(\Dout_emu[7]_OBUF_O_I ),
    .O(\Dout_emu[7] )
  );
  /* module_not_derived = 1 */
  /* src = "../../counter16_wrapper.v:43.5-63.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE \Dout_emu[7]_OBUF_O_I_DFFE_Q  (
    .CE(get_emu_IBUF_I_O_LUT2_I1_F),
    .CLK(clk_emu_IBUF_I_O),
    .D(\vectOut[1][7]_LUT4_I2_F ),
    .Q(\Dout_emu[7]_OBUF_O_I )
  );
  /* keep = 1 */
  IBUF clk_emu_IBUF_I (
    .I(clk_emu),
    .O(clk_emu_IBUF_I_O)
  );
  /* keep = 1 */
  IBUF get_emu_IBUF_I (
    .I(get_emu),
    .O(get_emu_IBUF_I_O)
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:139.23-140.26" */
  LUT2 get_emu_IBUF_I_O_LUT2_I1 (
    .F(get_emu_IBUF_I_O_LUT2_I1_F),
    .I0(load_emu_IBUF_I_O),
    .I1(get_emu_IBUF_I_O)
  );
  defparam get_emu_IBUF_I_O_LUT2_I1.INIT = 4'h1;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:139.23-140.26" */
  LUT2 get_emu_IBUF_I_O_LUT2_I1_1 (
    .F(get_emu_IBUF_I_O_LUT2_I1_1_F),
    .I0(load_emu_IBUF_I_O),
    .I1(get_emu_IBUF_I_O)
  );
  defparam get_emu_IBUF_I_O_LUT2_I1_1.INIT = 4'h4;
  /* keep = 1 */
  IBUF load_emu_IBUF_I (
    .I(load_emu),
    .O(load_emu_IBUF_I_O)
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE nCLR_DFFE_Q (
    .CE(load_emu_IBUF_I_O),
    .CLK(clk_emu_IBUF_I_O),
    .D(\stimIn[0][5] ),
    .Q(nCLR)
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:135.23-136.15" */
  LUT1 nCLR_LUT1_I0 (
    .F(nCLR_LUT1_I0_F),
    .I0(nCLR)
  );
  defparam nCLR_LUT1_I0.INIT = 2'h1;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE nLOAD_DFFE_Q (
    .CE(load_emu_IBUF_I_O),
    .CLK(clk_emu_IBUF_I_O),
    .D(\stimIn[0][4] ),
    .Q(nLOAD)
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE \stimIn[0][0]_DFFE_Q  (
    .CE(get_emu_IBUF_I_O_LUT2_I1_F),
    .CLK(clk_emu_IBUF_I_O),
    .D(\stimIn[0][0]_DFFE_Q_D ),
    .Q(\stimIn[0][0] )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE \stimIn[0][1]_DFFE_Q  (
    .CE(get_emu_IBUF_I_O_LUT2_I1_F),
    .CLK(clk_emu_IBUF_I_O),
    .D(\stimIn[0][1]_DFFE_Q_D ),
    .Q(\stimIn[0][1] )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE \stimIn[0][2]_DFFE_Q  (
    .CE(get_emu_IBUF_I_O_LUT2_I1_F),
    .CLK(clk_emu_IBUF_I_O),
    .D(\stimIn[0][2]_DFFE_Q_D ),
    .Q(\stimIn[0][2] )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE \stimIn[0][3]_DFFE_Q  (
    .CE(get_emu_IBUF_I_O_LUT2_I1_F),
    .CLK(clk_emu_IBUF_I_O),
    .D(\stimIn[0][3]_DFFE_Q_D ),
    .Q(\stimIn[0][3] )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE \stimIn[0][4]_DFFE_Q  (
    .CE(get_emu_IBUF_I_O_LUT2_I1_F),
    .CLK(clk_emu_IBUF_I_O),
    .D(\stimIn[0][4]_DFFE_Q_D ),
    .Q(\stimIn[0][4] )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE \stimIn[0][5]_DFFE_Q  (
    .CE(get_emu_IBUF_I_O_LUT2_I1_F),
    .CLK(clk_emu_IBUF_I_O),
    .D(\stimIn[0][5]_DFFE_Q_D ),
    .Q(\stimIn[0][5] )
  );
  GND \stimIn[0][6]_GND_G  (
    .G(\stimIn[0][6] )
  );
  /* keep = 1 */
  IBUF \u_counter16.CLK_IBUF_O  (
    .I(clk_dut),
    .O(\u_counter16.CLK )
  );
  /* module_not_derived = 1 */
  /* src = "../../counter16_wrapper.v:43.5-63.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE \vectOut[0][0]_DFFE_Q  (
    .CE(get_emu_IBUF_I_O_LUT2_I1_1_F),
    .CLK(clk_emu_IBUF_I_O),
    .D(\vectOut[0][0]_DFFE_Q_D ),
    .Q(\vectOut[0][0] )
  );
  /* module_not_derived = 1 */
  /* src = "../../../source/LS163.v:12.5-23.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:91.7-91.59" */
  DFFC \vectOut[0][0]_DFFE_Q_D_DFFC_Q  (
    .CLEAR(nCLR_LUT1_I0_F),
    .CLK(\u_counter16.CLK ),
    .D(\Din[0]_LUT3_I1_1_F ),
    .Q(\vectOut[0][0]_DFFE_Q_D )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT4 \vectOut[0][0]_LUT4_I2  (
    .F(\vectOut[2]_MUX2_LUT5_S0_I1 ),
    .I0(\Addr_emu[1]_IBUF_I_O ),
    .I1(\Addr_emu[0]_IBUF_I_O ),
    .I2(\vectOut[0][0] ),
    .I3(\vectOut[1][0] )
  );
  defparam \vectOut[0][0]_LUT4_I2 .INIT = 16'hf6b2;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT4 \vectOut[0][0]_LUT4_I2_1  (
    .F(\vectOut[2]_MUX2_LUT5_S0_I0 ),
    .I0(\Addr_emu[1]_IBUF_I_O ),
    .I1(\Addr_emu[0]_IBUF_I_O ),
    .I2(\vectOut[0][0] ),
    .I3(\vectOut[1][0] )
  );
  defparam \vectOut[0][0]_LUT4_I2_1 .INIT = 16'hd490;
  /* module_not_derived = 1 */
  /* src = "../../counter16_wrapper.v:43.5-63.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE \vectOut[0][1]_DFFE_Q  (
    .CE(get_emu_IBUF_I_O_LUT2_I1_1_F),
    .CLK(clk_emu_IBUF_I_O),
    .D(\Din[1]_LUT4_I0_1_F_DFFC_D_Q ),
    .Q(\vectOut[0][1] )
  );
  /* module_not_derived = 1 */
  /* src = "../../counter16_wrapper.v:43.5-63.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE \vectOut[0][2]_DFFE_Q  (
    .CE(get_emu_IBUF_I_O_LUT2_I1_1_F),
    .CLK(clk_emu_IBUF_I_O),
    .D(\vectOut[0][2]_DFFE_Q_D ),
    .Q(\vectOut[0][2] )
  );
  /* module_not_derived = 1 */
  /* src = "../../../source/LS163.v:12.5-23.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:91.7-91.59" */
  DFFC \vectOut[0][2]_DFFE_Q_D_DFFC_Q  (
    .CLEAR(nCLR_LUT1_I0_F),
    .CLK(\u_counter16.CLK ),
    .D(\vectOut[0][2]_DFFE_Q_D_DFFC_Q_D ),
    .Q(\vectOut[0][2]_DFFE_Q_D )
  );
  /* module_not_derived = 1 */
  /* src = "../../counter16_wrapper.v:43.5-63.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE \vectOut[0][3]_DFFE_Q  (
    .CE(get_emu_IBUF_I_O_LUT2_I1_1_F),
    .CLK(clk_emu_IBUF_I_O),
    .D(\vectOut[0][3]_DFFE_Q_D ),
    .Q(\vectOut[0][3] )
  );
  /* module_not_derived = 1 */
  /* src = "../../../source/LS163.v:12.5-23.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:91.7-91.59" */
  DFFC \vectOut[0][3]_DFFE_Q_D_DFFC_Q  (
    .CLEAR(nCLR_LUT1_I0_F),
    .CLK(\u_counter16.CLK ),
    .D(\Din[3]_LUT4_I0_F ),
    .Q(\vectOut[0][3]_DFFE_Q_D )
  );
  /* module_not_derived = 1 */
  /* src = "../../counter16_wrapper.v:43.5-63.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE \vectOut[0][4]_DFFE_Q  (
    .CE(get_emu_IBUF_I_O_LUT2_I1_1_F),
    .CLK(clk_emu_IBUF_I_O),
    .D(\vectOut[0][4]_DFFE_Q_D ),
    .Q(\vectOut[0][4] )
  );
  /* module_not_derived = 1 */
  /* src = "../../../source/LS163.v:12.5-23.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:115.8-115.68" */
  DFFCE \vectOut[0][4]_DFFE_Q_D_DFFCE_Q  (
    .CE(\vectOut[0][7]_DFFE_Q_D_DFFCE_Q_CE ),
    .CLEAR(nCLR_LUT1_I0_F),
    .CLK(\u_counter16.CLK ),
    .D(\Din[0]_LUT3_I1_F ),
    .Q(\vectOut[0][4]_DFFE_Q_D )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT4 \vectOut[0][4]_LUT4_I2  (
    .F(\vectOut[0][4]_LUT4_I2_F ),
    .I0(\Addr_emu[1]_IBUF_I_O ),
    .I1(\Addr_emu[0]_IBUF_I_O ),
    .I2(\vectOut[0][4] ),
    .I3(\vectOut[1][4] )
  );
  defparam \vectOut[0][4]_LUT4_I2 .INIT = 16'hd490;
  /* module_not_derived = 1 */
  /* src = "../../counter16_wrapper.v:43.5-63.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE \vectOut[0][5]_DFFE_Q  (
    .CE(get_emu_IBUF_I_O_LUT2_I1_1_F),
    .CLK(clk_emu_IBUF_I_O),
    .D(\vectOut[0][5]_DFFE_Q_D ),
    .Q(\vectOut[0][5] )
  );
  /* module_not_derived = 1 */
  /* src = "../../../source/LS163.v:12.5-23.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:115.8-115.68" */
  DFFCE \vectOut[0][5]_DFFE_Q_D_DFFCE_Q  (
    .CE(\vectOut[0][7]_DFFE_Q_D_DFFCE_Q_CE ),
    .CLEAR(nCLR_LUT1_I0_F),
    .CLK(\u_counter16.CLK ),
    .D(\Din[1]_LUT4_I0_F ),
    .Q(\vectOut[0][5]_DFFE_Q_D )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT4 \vectOut[0][5]_LUT4_I2  (
    .F(\vectOut[0][5]_LUT4_I2_F ),
    .I0(\Addr_emu[1]_IBUF_I_O ),
    .I1(\Addr_emu[0]_IBUF_I_O ),
    .I2(\vectOut[0][5] ),
    .I3(\vectOut[1][5] )
  );
  defparam \vectOut[0][5]_LUT4_I2 .INIT = 16'hd490;
  /* module_not_derived = 1 */
  /* src = "../../counter16_wrapper.v:43.5-63.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE \vectOut[0][6]_DFFE_Q  (
    .CE(get_emu_IBUF_I_O_LUT2_I1_1_F),
    .CLK(clk_emu_IBUF_I_O),
    .D(\vectOut[0][6]_DFFE_Q_D ),
    .Q(\vectOut[0][6] )
  );
  /* module_not_derived = 1 */
  /* src = "../../../source/LS163.v:12.5-23.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:115.8-115.68" */
  DFFCE \vectOut[0][6]_DFFE_Q_D_DFFCE_Q  (
    .CE(\vectOut[0][7]_DFFE_Q_D_DFFCE_Q_CE ),
    .CLEAR(nCLR_LUT1_I0_F),
    .CLK(\u_counter16.CLK ),
    .D(\vectOut[0][6]_DFFE_Q_D_DFFCE_Q_D ),
    .Q(\vectOut[0][6]_DFFE_Q_D )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT4 \vectOut[0][6]_LUT4_I2  (
    .F(\vectOut[0][6]_LUT4_I2_F ),
    .I0(\Addr_emu[1]_IBUF_I_O ),
    .I1(\Addr_emu[0]_IBUF_I_O ),
    .I2(\vectOut[0][6] ),
    .I3(\vectOut[1][6] )
  );
  defparam \vectOut[0][6]_LUT4_I2 .INIT = 16'hd490;
  /* module_not_derived = 1 */
  /* src = "../../counter16_wrapper.v:43.5-63.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE \vectOut[0][7]_DFFE_Q  (
    .CE(get_emu_IBUF_I_O_LUT2_I1_1_F),
    .CLK(clk_emu_IBUF_I_O),
    .D(\vectOut[0][7]_DFFE_Q_D ),
    .Q(\vectOut[0][7] )
  );
  /* module_not_derived = 1 */
  /* src = "../../../source/LS163.v:12.5-23.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:115.8-115.68" */
  DFFCE \vectOut[0][7]_DFFE_Q_D_DFFCE_Q  (
    .CE(\vectOut[0][7]_DFFE_Q_D_DFFCE_Q_CE ),
    .CLEAR(nCLR_LUT1_I0_F),
    .CLK(\u_counter16.CLK ),
    .D(\vectOut[0][7]_DFFE_Q_D_DFFCE_Q_D ),
    .Q(\vectOut[0][7]_DFFE_Q_D )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" */
  MUX2_LUT5 \vectOut[0][7]_DFFE_Q_D_DFFCE_Q_CE_MUX2_LUT5_O  (
    .I0(\vectOut[0][7]_DFFE_Q_D_DFFCE_Q_CE_MUX2_LUT5_O_I0 ),
    .I1(\vectOut[0][7]_DFFE_Q_D_DFFCE_Q_CE_MUX2_LUT5_O_I1 ),
    .O(\vectOut[0][7]_DFFE_Q_D_DFFCE_Q_CE ),
    .S0(\vectOut[0][0]_DFFE_Q_D )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT1 \vectOut[0][7]_DFFE_Q_D_DFFCE_Q_CE_MUX2_LUT5_O_I0_LUT1_F  (
    .F(\vectOut[0][7]_DFFE_Q_D_DFFCE_Q_CE_MUX2_LUT5_O_I0 ),
    .I0(nLOAD)
  );
  defparam \vectOut[0][7]_DFFE_Q_D_DFFCE_Q_CE_MUX2_LUT5_O_I0_LUT1_F .INIT = 2'h1;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT4 \vectOut[0][7]_DFFE_Q_D_DFFCE_Q_CE_MUX2_LUT5_O_I1_LUT4_F  (
    .F(\vectOut[0][7]_DFFE_Q_D_DFFCE_Q_CE_MUX2_LUT5_O_I1 ),
    .I0(nLOAD),
    .I1(\vectOut[0][3]_DFFE_Q_D ),
    .I2(\vectOut[0][2]_DFFE_Q_D ),
    .I3(\Din[1]_LUT4_I0_1_F_DFFC_D_Q )
  );
  defparam \vectOut[0][7]_DFFE_Q_D_DFFCE_Q_CE_MUX2_LUT5_O_I1_LUT4_F .INIT = 16'hd555;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT4 \vectOut[0][7]_DFFE_Q_D_LUT4_I2  (
    .F(\vectOut[0][7]_DFFE_Q_D_DFFCE_Q_D ),
    .I0(\Din[3] ),
    .I1(nLOAD),
    .I2(\vectOut[0][7]_DFFE_Q_D ),
    .I3(\vectOut[0][7]_DFFE_Q_D_LUT4_I2_I3 )
  );
  defparam \vectOut[0][7]_DFFE_Q_D_LUT4_I2 .INIT = 16'h2ee2;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:143.23-144.37" */
  LUT3 \vectOut[0][7]_DFFE_Q_D_LUT4_I2_I3_LUT3_F  (
    .F(\vectOut[0][7]_DFFE_Q_D_LUT4_I2_I3 ),
    .I0(\vectOut[0][5]_DFFE_Q_D ),
    .I1(\vectOut[0][6]_DFFE_Q_D ),
    .I2(\vectOut[0][4]_DFFE_Q_D )
  );
  defparam \vectOut[0][7]_DFFE_Q_D_LUT4_I2_I3_LUT3_F .INIT = 8'h80;
  /* module_not_derived = 1 */
  /* src = "../../counter16_wrapper.v:43.5-63.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE \vectOut[1][0]_DFFE_Q  (
    .CE(get_emu_IBUF_I_O_LUT2_I1_1_F),
    .CLK(clk_emu_IBUF_I_O),
    .D(\vectOut[1][0]_DFFE_Q_D ),
    .Q(\vectOut[1][0] )
  );
  /* module_not_derived = 1 */
  /* src = "../../counter16_wrapper.v:43.5-63.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE \vectOut[1][1]_DFFE_Q  (
    .CE(get_emu_IBUF_I_O_LUT2_I1_1_F),
    .CLK(clk_emu_IBUF_I_O),
    .D(\vectOut[1][1]_DFFE_Q_D ),
    .Q(\vectOut[1][1] )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT4 \vectOut[1][1]_LUT4_I2  (
    .F(\vectOut[1][1]_LUT4_I2_F ),
    .I0(\Addr_emu[1]_IBUF_I_O ),
    .I1(\Addr_emu[0]_IBUF_I_O ),
    .I2(\vectOut[1][1] ),
    .I3(\vectOut[0][1] )
  );
  defparam \vectOut[1][1]_LUT4_I2 .INIT = 16'hd940;
  /* module_not_derived = 1 */
  /* src = "../../counter16_wrapper.v:43.5-63.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE \vectOut[1][2]_DFFE_Q  (
    .CE(get_emu_IBUF_I_O_LUT2_I1_1_F),
    .CLK(clk_emu_IBUF_I_O),
    .D(\vectOut[1][2]_DFFE_Q_D ),
    .Q(\vectOut[1][2] )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT4 \vectOut[1][2]_LUT4_I2  (
    .F(\vectOut[1][2]_LUT4_I2_F ),
    .I0(\Addr_emu[1]_IBUF_I_O ),
    .I1(\Addr_emu[0]_IBUF_I_O ),
    .I2(\vectOut[1][2] ),
    .I3(\vectOut[0][2] )
  );
  defparam \vectOut[1][2]_LUT4_I2 .INIT = 16'hd940;
  /* module_not_derived = 1 */
  /* src = "../../counter16_wrapper.v:43.5-63.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE \vectOut[1][3]_DFFE_Q  (
    .CE(get_emu_IBUF_I_O_LUT2_I1_1_F),
    .CLK(clk_emu_IBUF_I_O),
    .D(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_I1_LUT4_F_I2_LUT4_I3_F_DFFCE_D_Q ),
    .Q(\vectOut[1][3] )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT4 \vectOut[1][3]_LUT4_I2  (
    .F(\vectOut[1][3]_LUT4_I2_F ),
    .I0(\Addr_emu[1]_IBUF_I_O ),
    .I1(\Addr_emu[0]_IBUF_I_O ),
    .I2(\vectOut[1][3] ),
    .I3(\vectOut[0][3] )
  );
  defparam \vectOut[1][3]_LUT4_I2 .INIT = 16'hd940;
  /* module_not_derived = 1 */
  /* src = "../../counter16_wrapper.v:43.5-63.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE \vectOut[1][4]_DFFE_Q  (
    .CE(get_emu_IBUF_I_O_LUT2_I1_1_F),
    .CLK(clk_emu_IBUF_I_O),
    .D(\vectOut[1][4]_DFFE_Q_D ),
    .Q(\vectOut[1][4] )
  );
  /* module_not_derived = 1 */
  /* src = "../../counter16_wrapper.v:43.5-63.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE \vectOut[1][5]_DFFE_Q  (
    .CE(get_emu_IBUF_I_O_LUT2_I1_1_F),
    .CLK(clk_emu_IBUF_I_O),
    .D(\vectOut[1][5]_DFFE_Q_D ),
    .Q(\vectOut[1][5] )
  );
  /* module_not_derived = 1 */
  /* src = "../../counter16_wrapper.v:43.5-63.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE \vectOut[1][6]_DFFE_Q  (
    .CE(get_emu_IBUF_I_O_LUT2_I1_1_F),
    .CLK(clk_emu_IBUF_I_O),
    .D(\vectOut[1][6]_DFFE_Q_D ),
    .Q(\vectOut[1][6] )
  );
  /* module_not_derived = 1 */
  /* src = "../../../source/LS163.v:12.5-23.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:115.8-115.68" */
  DFFCE \vectOut[1][6]_DFFE_Q_D_DFFCE_Q  (
    .CE(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_LUT3_I2_F ),
    .CLEAR(nCLR_LUT1_I0_F),
    .CLK(\u_counter16.CLK ),
    .D(\vectOut[1][6]_DFFE_Q_D_DFFCE_Q_D ),
    .Q(\vectOut[1][6]_DFFE_Q_D )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:143.23-144.37" */
  LUT3 \vectOut[1][6]_DFFE_Q_D_LUT3_I2  (
    .F(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_I1_LUT4_F_I3 ),
    .I0(\vectOut[1][4]_DFFE_Q_D ),
    .I1(\vectOut[1][5]_DFFE_Q_D ),
    .I2(\vectOut[1][6]_DFFE_Q_D )
  );
  defparam \vectOut[1][6]_DFFE_Q_D_LUT3_I2 .INIT = 8'h80;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" */
  MUX2_LUT5 \vectOut[1][6]_DFFE_Q_D_MUX2_LUT5_S0  (
    .I0(\vectOut[1][6]_DFFE_Q_D_MUX2_LUT5_S0_I0 ),
    .I1(\vectOut[1][6]_DFFE_Q_D_MUX2_LUT5_S0_I1 ),
    .O(\vectOut[1][6]_DFFE_Q_D_DFFCE_Q_D ),
    .S0(\vectOut[1][6]_DFFE_Q_D )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT4 \vectOut[1][6]_DFFE_Q_D_MUX2_LUT5_S0_I0_LUT4_F  (
    .F(\vectOut[1][6]_DFFE_Q_D_MUX2_LUT5_S0_I0 ),
    .I0(\Din[2] ),
    .I1(nLOAD),
    .I2(\vectOut[1][4]_DFFE_Q_D ),
    .I3(\vectOut[1][5]_DFFE_Q_D )
  );
  defparam \vectOut[1][6]_DFFE_Q_D_MUX2_LUT5_S0_I0_LUT4_F .INIT = 16'he222;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT4 \vectOut[1][6]_DFFE_Q_D_MUX2_LUT5_S0_I1_LUT4_F  (
    .F(\vectOut[1][6]_DFFE_Q_D_MUX2_LUT5_S0_I1 ),
    .I0(\Din[2] ),
    .I1(nLOAD),
    .I2(\vectOut[1][4]_DFFE_Q_D ),
    .I3(\vectOut[1][5]_DFFE_Q_D )
  );
  defparam \vectOut[1][6]_DFFE_Q_D_MUX2_LUT5_S0_I1_LUT4_F .INIT = 16'h2eee;
  /* module_not_derived = 1 */
  /* src = "../../counter16_wrapper.v:43.5-63.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE \vectOut[1][7]_DFFE_Q  (
    .CE(get_emu_IBUF_I_O_LUT2_I1_1_F),
    .CLK(clk_emu_IBUF_I_O),
    .D(\vectOut[1][7]_DFFE_Q_D ),
    .Q(\vectOut[1][7] )
  );
  /* module_not_derived = 1 */
  /* src = "../../../source/LS163.v:12.5-23.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:115.8-115.68" */
  DFFCE \vectOut[1][7]_DFFE_Q_D_DFFCE_Q  (
    .CE(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_LUT3_I2_F ),
    .CLEAR(nCLR_LUT1_I0_F),
    .CLK(\u_counter16.CLK ),
    .D(\vectOut[1][7]_DFFE_Q_D_DFFCE_Q_D ),
    .Q(\vectOut[1][7]_DFFE_Q_D )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT4 \vectOut[1][7]_DFFE_Q_D_LUT4_I2  (
    .F(\vectOut[1][7]_DFFE_Q_D_DFFCE_Q_D ),
    .I0(\Din[3] ),
    .I1(nLOAD),
    .I2(\vectOut[1][7]_DFFE_Q_D ),
    .I3(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_I1_LUT4_F_I3 )
  );
  defparam \vectOut[1][7]_DFFE_Q_D_LUT4_I2 .INIT = 16'h2ee2;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT4 \vectOut[1][7]_LUT4_I2  (
    .F(\vectOut[1][7]_LUT4_I2_F ),
    .I0(\Addr_emu[1]_IBUF_I_O ),
    .I1(\Addr_emu[0]_IBUF_I_O ),
    .I2(\vectOut[1][7] ),
    .I3(\vectOut[0][7] )
  );
  defparam \vectOut[1][7]_LUT4_I2 .INIT = 16'hd940;
  /* module_not_derived = 1 */
  /* src = "../../counter16_wrapper.v:43.5-63.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:19.7-19.56" */
  DFFE \vectOut[2]_DFFE_Q  (
    .CE(get_emu_IBUF_I_O_LUT2_I1_1_F),
    .CLK(clk_emu_IBUF_I_O),
    .D(\vectOut[2]_DFFE_Q_D ),
    .Q(\vectOut[2] )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" */
  MUX2_LUT5 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O  (
    .I0(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_I0 ),
    .I1(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_I1 ),
    .O(\vectOut[2]_DFFE_Q_D ),
    .S0(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0 )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT1 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_I0_LUT1_F  (
    .F(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_I0 ),
    .I0(\stimIn[0][6] )
  );
  defparam \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_I0_LUT1_F .INIT = 2'h0;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT4 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_I1_LUT4_F  (
    .F(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_I1 ),
    .I0(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_I1_LUT4_F_I2_LUT4_I3_F_DFFCE_D_Q ),
    .I1(\vectOut[1][7]_DFFE_Q_D ),
    .I2(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_I1_LUT4_F_I2 ),
    .I3(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_I1_LUT4_F_I3 )
  );
  defparam \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_I1_LUT4_F .INIT = 16'h8000;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:143.23-144.37" */
  LUT3 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_I1_LUT4_F_I2_LUT3_F  (
    .F(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_I1_LUT4_F_I2 ),
    .I0(\vectOut[1][0]_DFFE_Q_D ),
    .I1(\vectOut[1][1]_DFFE_Q_D ),
    .I2(\vectOut[1][2]_DFFE_Q_D )
  );
  defparam \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_I1_LUT4_F_I2_LUT3_F .INIT = 8'h80;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT4 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_I1_LUT4_F_I2_LUT4_I3  (
    .F(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_I1_LUT4_F_I2_LUT4_I3_F ),
    .I0(\Din[3] ),
    .I1(nLOAD),
    .I2(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_I1_LUT4_F_I2_LUT4_I3_F_DFFCE_D_Q ),
    .I3(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_I1_LUT4_F_I2 )
  );
  defparam \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_I1_LUT4_F_I2_LUT4_I3 .INIT = 16'h2ee2;
  /* module_not_derived = 1 */
  /* src = "../../../source/LS163.v:12.5-23.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:115.8-115.68" */
  DFFCE \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_I1_LUT4_F_I2_LUT4_I3_F_DFFCE_D  (
    .CE(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_LUT2_I1_F ),
    .CLEAR(nCLR_LUT1_I0_F),
    .CLK(\u_counter16.CLK ),
    .D(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_I1_LUT4_F_I2_LUT4_I3_F ),
    .Q(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_I1_LUT4_F_I2_LUT4_I3_F_DFFCE_D_Q )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:139.23-140.26" */
  LUT2 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_LUT2_I1  (
    .F(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_LUT2_I1_F ),
    .I0(nLOAD),
    .I1(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0 )
  );
  defparam \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_LUT2_I1 .INIT = 4'hd;
  /* module_not_derived = 1 */
  /* src = "../../../source/LS163.v:12.5-23.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:115.8-115.68" */
  DFFCE \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_LUT2_I1_F_DFFCE_CE  (
    .CE(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_LUT2_I1_F ),
    .CLEAR(nCLR_LUT1_I0_F),
    .CLK(\u_counter16.CLK ),
    .D(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_LUT2_I1_F_DFFCE_CE_D ),
    .Q(\vectOut[1][2]_DFFE_Q_D )
  );
  /* module_not_derived = 1 */
  /* src = "../../../source/LS163.v:12.5-23.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:115.8-115.68" */
  DFFCE \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_LUT2_I1_F_DFFCE_CE_1  (
    .CE(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_LUT2_I1_F ),
    .CLEAR(nCLR_LUT1_I0_F),
    .CLK(\u_counter16.CLK ),
    .D(\Din[1]_LUT4_I0_2_F ),
    .Q(\vectOut[1][1]_DFFE_Q_D )
  );
  /* module_not_derived = 1 */
  /* src = "../../../source/LS163.v:12.5-23.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:115.8-115.68" */
  DFFCE \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_LUT2_I1_F_DFFCE_CE_2  (
    .CE(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_LUT2_I1_F ),
    .CLEAR(nCLR_LUT1_I0_F),
    .CLK(\u_counter16.CLK ),
    .D(\Din[0]_LUT3_I1_2_F ),
    .Q(\vectOut[1][0]_DFFE_Q_D )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:143.23-144.37" */
  LUT3 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_LUT3_I2  (
    .F(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_LUT3_I2_F ),
    .I0(nLOAD),
    .I1(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_LUT3_I2_I1 ),
    .I2(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0 )
  );
  defparam \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_LUT3_I2 .INIT = 8'hd5;
  /* module_not_derived = 1 */
  /* src = "../../../source/LS163.v:12.5-23.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:115.8-115.68" */
  DFFCE \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_LUT3_I2_F_DFFCE_CE  (
    .CE(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_LUT3_I2_F ),
    .CLEAR(nCLR_LUT1_I0_F),
    .CLK(\u_counter16.CLK ),
    .D(\Din[1]_LUT4_I0_3_F ),
    .Q(\vectOut[1][5]_DFFE_Q_D )
  );
  /* module_not_derived = 1 */
  /* src = "../../../source/LS163.v:12.5-23.8|/usr/local/bin/../share/yosys/gowin/cells_map.v:115.8-115.68" */
  DFFCE \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_LUT3_I2_F_DFFCE_CE_1  (
    .CE(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_LUT3_I2_F ),
    .CLEAR(nCLR_LUT1_I0_F),
    .CLK(\u_counter16.CLK ),
    .D(\Din[0]_LUT3_I1_3_F ),
    .Q(\vectOut[1][4]_DFFE_Q_D )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT4 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_LUT3_I2_I1_LUT4_F  (
    .F(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_LUT3_I2_I1 ),
    .I0(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_I1_LUT4_F_I2_LUT4_I3_F_DFFCE_D_Q ),
    .I1(\vectOut[1][0]_DFFE_Q_D ),
    .I2(\vectOut[1][1]_DFFE_Q_D ),
    .I3(\vectOut[1][2]_DFFE_Q_D )
  );
  defparam \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_LUT3_I2_I1_LUT4_F .INIT = 16'h8000;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:172.14-172.54" */
  MUX2_LUT8 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O  (
    .I0(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0 ),
    .I1(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1 ),
    .O(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0 ),
    .S0(\vectOut[0][7]_DFFE_Q_D )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:166.14-166.54" */
  MUX2_LUT7 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O  (
    .I0(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0 ),
    .I1(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1 ),
    .O(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0 ),
    .S0(\vectOut[0][0]_DFFE_Q_D )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:160.14-160.54" */
  MUX2_LUT6 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O  (
    .I0(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0 ),
    .I1(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1 ),
    .O(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0 ),
    .S0(\vectOut[0][4]_DFFE_Q_D )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" */
  MUX2_LUT5 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O  (
    .I0(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ),
    .I1(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ),
    .O(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0 ),
    .S0(\Din[1]_LUT4_I0_1_F_DFFC_D_Q )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT1 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0_LUT1_F  (
    .F(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ),
    .I0(\stimIn[0][6] )
  );
  defparam \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0_LUT1_F .INIT = 2'h0;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT1 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1_LUT1_F  (
    .F(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ),
    .I0(\stimIn[0][6] )
  );
  defparam \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1_LUT1_F .INIT = 2'h0;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" */
  MUX2_LUT5 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O  (
    .I0(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ),
    .I1(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ),
    .O(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1 ),
    .S0(\Din[1]_LUT4_I0_1_F_DFFC_D_Q )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT1 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0_LUT1_F  (
    .F(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ),
    .I0(\stimIn[0][6] )
  );
  defparam \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0_LUT1_F .INIT = 2'h0;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT1 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1_LUT1_F  (
    .F(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ),
    .I0(\stimIn[0][6] )
  );
  defparam \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1_LUT1_F .INIT = 2'h0;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:160.14-160.54" */
  MUX2_LUT6 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O  (
    .I0(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0 ),
    .I1(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1 ),
    .O(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1 ),
    .S0(\vectOut[0][4]_DFFE_Q_D )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" */
  MUX2_LUT5 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O  (
    .I0(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ),
    .I1(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ),
    .O(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0 ),
    .S0(\Din[1]_LUT4_I0_1_F_DFFC_D_Q )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT1 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0_LUT1_F  (
    .F(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ),
    .I0(\stimIn[0][6] )
  );
  defparam \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0_LUT1_F .INIT = 2'h0;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT1 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1_LUT1_F  (
    .F(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ),
    .I0(\stimIn[0][6] )
  );
  defparam \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1_LUT1_F .INIT = 2'h0;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" */
  MUX2_LUT5 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O  (
    .I0(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ),
    .I1(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ),
    .O(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1 ),
    .S0(\Din[1]_LUT4_I0_1_F_DFFC_D_Q )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT1 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0_LUT1_F  (
    .F(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ),
    .I0(\stimIn[0][6] )
  );
  defparam \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0_LUT1_F .INIT = 2'h0;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:170.42-170.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT1 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1_LUT1_F  (
    .F(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ),
    .I0(\stimIn[0][6] )
  );
  defparam \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I0_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1_LUT1_F .INIT = 2'h0;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/local/bin/../share/yosys/gowin/cells_map.v:166.14-166.54" */
  MUX2_LUT7 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O  (
    .I0(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0 ),
    .I1(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1 ),
    .O(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1 ),
    .S0(\vectOut[0][0]_DFFE_Q_D )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/local/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:160.14-160.54" */
  MUX2_LUT6 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O  (
    .I0(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0 ),
    .I1(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1 ),
    .O(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0 ),
    .S0(\vectOut[0][4]_DFFE_Q_D )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/local/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" */
  MUX2_LUT5 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O  (
    .I0(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ),
    .I1(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ),
    .O(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0 ),
    .S0(\Din[1]_LUT4_I0_1_F_DFFC_D_Q )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/local/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT1 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0_LUT1_F  (
    .F(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ),
    .I0(\stimIn[0][6] )
  );
  defparam \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0_LUT1_F .INIT = 2'h0;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/local/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT1 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1_LUT1_F  (
    .F(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ),
    .I0(\stimIn[0][6] )
  );
  defparam \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1_LUT1_F .INIT = 2'h0;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/local/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" */
  MUX2_LUT5 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O  (
    .I0(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ),
    .I1(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ),
    .O(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1 ),
    .S0(\Din[1]_LUT4_I0_1_F_DFFC_D_Q )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/local/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT1 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0_LUT1_F  (
    .F(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ),
    .I0(\stimIn[0][6] )
  );
  defparam \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0_LUT1_F .INIT = 2'h0;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/local/bin/../share/yosys/gowin/cells_map.v:164.41-164.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT1 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1_LUT1_F  (
    .F(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ),
    .I0(\stimIn[0][6] )
  );
  defparam \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I0_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1_LUT1_F .INIT = 2'h0;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/local/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:160.14-160.54" */
  MUX2_LUT6 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O  (
    .I0(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0 ),
    .I1(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1 ),
    .O(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1 ),
    .S0(\vectOut[0][4]_DFFE_Q_D )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/local/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" */
  MUX2_LUT5 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O  (
    .I0(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ),
    .I1(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ),
    .O(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0 ),
    .S0(\Din[1]_LUT4_I0_1_F_DFFC_D_Q )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/local/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT1 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0_LUT1_F  (
    .F(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0 ),
    .I0(\stimIn[0][6] )
  );
  defparam \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I0_LUT1_F .INIT = 2'h0;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/local/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:158.41-158.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT1 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1_LUT1_F  (
    .F(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1 ),
    .I0(\stimIn[0][6] )
  );
  defparam \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I0_MUX2_LUT5_O_I1_LUT1_F .INIT = 2'h0;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/local/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" */
  MUX2_LUT5 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O  (
    .I0(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ),
    .I1(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ),
    .O(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1 ),
    .S0(\Din[1]_LUT4_I0_1_F_DFFC_D_Q )
  );
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/local/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:152.41-152.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT1 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0_LUT1_F  (
    .F(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0 ),
    .I0(\stimIn[0][6] )
  );
  defparam \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I0_LUT1_F .INIT = 2'h0;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:171.43-171.68|/usr/local/bin/../share/yosys/gowin/cells_map.v:165.42-165.67|/usr/local/bin/../share/yosys/gowin/cells_map.v:159.41-159.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:153.41-153.66|/usr/local/bin/../share/yosys/gowin/cells_map.v:147.23-148.48" */
  LUT4 \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1_LUT4_F  (
    .F(\vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1 ),
    .I0(\vectOut[0][3]_DFFE_Q_D ),
    .I1(\vectOut[0][2]_DFFE_Q_D ),
    .I2(\vectOut[0][5]_DFFE_Q_D ),
    .I3(\vectOut[0][6]_DFFE_Q_D )
  );
  defparam \vectOut[2]_DFFE_Q_D_MUX2_LUT5_O_S0_MUX2_LUT8_O_I1_MUX2_LUT7_O_I1_MUX2_LUT6_O_I1_MUX2_LUT5_O_I1_LUT4_F .INIT = 16'h8000;
  /* module_not_derived = 1 */
  /* src = "/usr/local/bin/../share/yosys/gowin/cells_map.v:154.14-154.54" */
  MUX2_LUT5 \vectOut[2]_MUX2_LUT5_S0  (
    .I0(\vectOut[2]_MUX2_LUT5_S0_I0 ),
    .I1(\vectOut[2]_MUX2_LUT5_S0_I1 ),
    .O(\vectOut[2]_MUX2_LUT5_S0_O ),
    .S0(\vectOut[2] )
  );
  assign \u_counter16.u_LS163x1.Din[0]  = \Din[0] ;
  assign \u_counter16.u_LS163x1.Din[1]  = \Din[1] ;
  assign \u_counter16.u_LS163x1.Din[2]  = \Din[2] ;
  assign \u_counter16.u_LS163x1.Din[3]  = \Din[3] ;
  assign \u_counter16.Din[3]  = \Din[3] ;
  assign \u_counter16.Din[2]  = \Din[2] ;
  assign \u_counter16.Din[1]  = \Din[1] ;
  assign \u_counter16.Din[0]  = \Din[0] ;
  assign \u_counter16.u_LS163x3.Din[0]  = \Din[0] ;
  assign \u_counter16.u_LS163x3.Din[1]  = \Din[1] ;
  assign \u_counter16.u_LS163x3.Din[2]  = \Din[2] ;
  assign \u_counter16.u_LS163x0.Din[0]  = \Din[0] ;
  assign \u_counter16.u_LS163x0.Din[1]  = \Din[1] ;
  assign \u_counter16.u_LS163x0.Din[2]  = \Din[2] ;
  assign \u_counter16.u_LS163x0.Din[3]  = \Din[3] ;
  assign \u_counter16.u_LS163x3.Din[3]  = \Din[3] ;
  assign \stimIn[0][7]  = \stimIn[0][6] ;
  assign \u_counter16.u_LS163x2.Din[0]  = \Din[0] ;
  assign \u_counter16.u_LS163x2.Din[1]  = \Din[1] ;
  assign \u_counter16.u_LS163x2.Din[2]  = \Din[2] ;
  assign \u_counter16.u_LS163x2.Din[3]  = \Din[3] ;
  assign \u_counter16.nCLR  = nCLR;
  assign \u_counter16.nLOAD  = nLOAD;
  assign \u_counter16.u_LS163x0.CLK  = \u_counter16.CLK ;
  assign \u_counter16.u_LS163x0.nCLR  = nCLR;
  assign \u_counter16.u_LS163x0.nLOAD  = nLOAD;
  assign \u_counter16.u_LS163x1.CLK  = \u_counter16.CLK ;
  assign \u_counter16.u_LS163x1.nCLR  = nCLR;
  assign \u_counter16.u_LS163x1.nLOAD  = nLOAD;
  assign \u_counter16.u_LS163x2.CLK  = \u_counter16.CLK ;
  assign \u_counter16.u_LS163x2.nCLR  = nCLR;
  assign \u_counter16.u_LS163x2.nLOAD  = nLOAD;
  assign \u_counter16.u_LS163x3.CLK  = \u_counter16.CLK ;
  assign \u_counter16.u_LS163x3.nCLR  = nCLR;
  assign \u_counter16.u_LS163x3.nLOAD  = nLOAD;
endmodule
